import "./globals.css";

import { Navigation } from "@/components/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        <div className="mx-auto flex min-h-screen sm:max-w-2xl sm:gap-x-3 sm:px-4">
          <Navigation />
          <div className="flex-1 overflow-hidden bg-mauve-3 pb-20 sm:border-x">{children}</div>
        </div>
      </body>
    </html>
  );
}
