import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import { Navigation } from "@/components/navigation";
import { ToastProvider } from "@/providers/toast-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="bg-mauve-1">
        <ToastProvider>
          <div className="mx-auto flex min-h-screen sm:max-w-3xl sm:gap-x-3 sm:px-4">
            <Navigation />
            <div className="max-w-[390px] grow overflow-hidden pb-20 sm:border-x sm:border-mauve-6 md:max-w-[480px]">
              {children}
            </div>
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}
